export type Language = 'ar' | 'en'
export type Category = 'all' | 'electronics' | 'home' | 'beauty' | 'audio'

export interface Product {
  id: string
  category: Exclude<Category, 'all'>
  title: Record<Language, string>
  price: number
  image: string
}

export const products: Product[] = [
  {
    id: 'p001',
    category: 'home',
    title: { ar: 'مرطب هواء RGB دائري', en: 'RGB Air Humidifier' },
    price: 14.,
    image: '/products/p001.jpg',
  },
  {
    id: 'p002',
    category: 'electronics',
    title: { ar: 'بروجكتر صغير محمول', en: 'Mini Portable Projector' },
    price: 19,
    image: '/products/p002.jpg',
  },
  {
    id: 'p003',
    category: 'electronics',
    title: { ar: 'باور بانك 60000mAh مع فانوس', en: '60000mAh Power Bank with Lantern' },
    price: 11,
    image: '/products/p003.jpg',
  },
  {
    id: 'p004',
    category: 'home',
    title: { ar: 'مروحة يد صغيرة محمولة', en: 'Mini Handheld Fan' },
    price: 8,
    image: '/products/p004.jpg',
  },
  {
    id: 'p005',
    category: 'audio',
    title: { ar: 'سماعة قرآن بلوتوث مع ريموت', en: 'Quran Bluetooth Speaker with Remote' },
    price: 12,
    image: '/products/p005.jpg',
  },
  {
    id: 'p006',
    category: 'electronics',
    title: { ar: 'بروجكتر ذكي 4K واي فاي وبلوتوث', en: 'Smart 4K Projector WiFi/BT' },
    price: 28,
    image: '/products/p006.jpg',
  },
  {
    id: 'p007',
    category: 'home',
    title: { ar: 'ماكينة قهوة RAF 3 في 1', en: 'RAF 3-in-1 Coffee Maker' },
    price: 24,
    image: '/products/p007.jpg',
  },
  {
    id: 'p008',
    category: 'electronics',
    title: { ar: 'طقم لوحة مفاتيح وماوس لاسلكي', en: 'Wireless Keyboard & Mouse Set' },
    price: 10,
    image: '/products/p008.jpg',
  },
  {
    id: 'p009',
    category: 'electronics',
    title: { ar: 'حامل جوال للسيارة بتتبع ذكي', en: 'AI Tracking Car Phone Holder' },
    price: 13,
    image: '/products/p009.jpg',
  },
  {
    id: 'p010',
    category: 'electronics',
    title: { ar: 'جهاز لوحي "F17" بغطاء لوحة مفاتيح', en: 'F17 Tablet with Keyboard Cover' },
    price: 32,
    image: '/products/p010.jpg',
  },
  {
    id: 'p011',
    category: 'beauty',
    title: { ar: 'ماكينة حلاقة صغيرة برؤوس بديلة', en: 'Mini Electric Shaver w/ Heads' },
    price: 12,
    image: '/products/p011.jpg',
  },
  {
    id: 'p012',
    category: 'home',
    title: { ar: 'خلاط يدوي RAF بقوة 1600 واط', en: 'RAF 1600W Hand Blender' },
    price: 12,
    image: '/products/p012.jpg',
  },
  {
    id: 'p013',
    category: 'beauty',
    title: { ar: 'ماكينة تشذيب لحية BIAOYA', en: 'BIAOYA Beard Trimmer' },
    price: 14,
    image: '/products/p013.jpg',
  },
  {
    id: 'p014',
    category: 'home',
    title: { ar: 'قلاية هوائية Silver Crest 10 لتر', en: 'Silver Crest Air Fryer 10L' },
    price: 23,
    image: '/products/p014.jpg',
  },
  {
    id: 'p015',
    category: 'electronics',
    title: { ar: 'كاميرا واي فاي صغيرة (زوج)', en: 'Mini WiFi Camera (Pair)' },
    price: 15,
    image: '/products/p015.jpg',
  },
  {
    id: 'p016',
    category: 'electronics',
    title: { ar: 'كاميرا مراقبة خارجية دوارة مع SD', en: 'Outdoor PTZ Camera w/ SD' },
    price: 16,
    image: '/products/p016.jpg',
  },
  {
    id: 'p017',
    category: 'home',
    title: { ar: 'شريط إضاءة LED نيون RGB بتطبيق', en: 'LED Neon RGB Strip w/ App' },
    price: 10,
    image: '/products/p017.jpg',
  },
  {
    id: 'p019',
    category: 'electronics',
    title: { ar: 'كاميرا مراقبة خارجية بطاقة شمسية', en: 'Solar Outdoor PTZ Camera' },
    price: 26,
    image: '/products/p019.jpg',
  },
  {
    id: 'p020',
    category: 'electronics',
    title: { ar: 'بروجكتر ألعاب مع يدين تحكم', en: 'Gaming Projector w/ 2 Controllers' },
    price: 29,
    image: '/products/p020.jpg',
  },
  {
    id: 'p021',
    category: 'beauty',
    title: { ar: 'مكواة فرد شعر احترافية SOKANY', en: 'SOKANY Pro Hair Straightener' },
    price: 9,
    image: '/products/p021.jpg',
  },
  {
    id: 'p022',
    category: 'beauty',
    title: { ar: 'ولاعة كهربائية قابلة لاعادة الشحن', en: 'Light Pore Cleanser Device' },
    price: 9,
    image: '/products/p022.jpg',
  },
  {
    id: 'p023',
    category: 'audio',
    title: { ar: 'سماعة رأس سلكية ASD', en: 'ASD Wired Headphone' },
    price: 10,
    image: '/products/p023.jpg',
  },
  {
    id: 'p024',
    category: 'home',
    title: { ar: 'لوحة نيون LED حسب الطلب (تصاميم متعددة)', en: 'Custom LED Neon Sign' },
    price: 12,
    image: '/products/p024.jpg',
  },
  {
    id: 'p025',
    category: 'electronics',
    title: { ar: 'Tiger TV Box جهاز بث أندرويد 4K', en: 'Tiger TV Box Android 4K' },
    price: 16,
    image: '/products/p025.jpg',
  },
  {
    id: 'p026',
    category: 'home',
    title: { ar: 'آلة فشار كهربائية هوائية', en: 'Electric Hot Air Popcorn Maker' },
    price: 14,
    image: '/products/p026.jpg',
  },
  {
    id: 'p027',
    category: 'audio',
    title: { ar: 'سماعة القرآن الكريم المحمولة (سندس)', en: 'Sundus Portable Quran Speaker' },
    price: 14,
    image: '/products/p027.jpg',
  },
  {
    id: 'p028',
    category: 'electronics',
    title: { ar: 'باور بانك Redmi أبيض', en: 'Redmi White Power Bank' },
    price: 13,
    image: '/products/p028.jpg',
  },
  {
    id: 'p029',
    category: 'audio',
    title: { ar: 'سماعة كاريوكي بلوتوث مع مايك (زوج)', en: 'Karaoke BT Speaker w/ Mic (Pair)' },
    price: 12,
    image: '/products/p029.jpg',
  },
  {
    id: 'p030',
    category: 'home',
    title: { ar: 'شواية ستيك كهربائية RAF', en: 'RAF Electric Steak Machine' },
    price: 15,
    image: '/products/p030.jpg',
  },
  {
    id: 'p031',
    category: 'home',
    title: { ar: 'مروحة يد محمولة بشاشة شحن', en: 'Handheld Fan w/ Battery Display' },
    price: 11,
    image: '/products/p031.jpg',
  },
  {
    id: 'p032',
    category: 'home',
    title: { ar: 'مصباح إسقاط نجوم ليلي للأطفال', en: 'Kids Star Projector Night Lamp' },
    price: 10,
    image: '/products/p032.jpg',
  },
  {
    id: 'p033',
    category: 'beauty',
    title: { ar: 'فرشاة تدليك فروة الرأس', en: 'Scalp Massage Brush' },
    price: 11,
    image: '/products/p033.jpg',
  },
  {
    id: 'p034',
    category: 'beauty',
    title: { ar: 'فرشاة فرد شعر حرارية بشاشة رقمية', en: 'Heated Straightening Brush LCD' },
    price: 12,
    image: '/products/p034.jpg',
  },
  {
    id: 'p035',
    category: 'audio',
    title: { ar: 'سماعات أذن لاسلكية ASD', en: 'ASD Wireless Earbuds' },
    price: 10,
    image: '/products/p035.jpg',
  },
  {
    id: 'p036',
    category: 'electronics',
    title: { ar: 'طقم ساعة ذكية A58 Plus مع إكسسوارات', en: 'A58 Plus Smartwatch Gift Set' },
    price: 11,
    image: '/products/p036.jpg',
  },
  {
    id: 'p037',
    category: 'home',
    title: { ar: 'ماكينة قهوة RAF لكوبين', en: 'RAF 2-Cup Coffee Maker' },
    price: 13,
    image: '/products/p037.jpg',
  },
  {
    id: 'p038',
    category: 'home',
    title: { ar: 'إبريق قهوة تركي كهربائي RAF', en: 'RAF Electric Turkish Coffee Pot' },
    price: 16,
    image: '/products/p038.jpg',
  },
  {
    id: 'p039',
    category: 'electronics',
    title: { ar: 'نظارة شمسية بسماعة بلوتوث مدمجة', en: 'Bluetooth Audio Sunglasses' },
    price: 9,
    image: '/products/p039.jpg',
  },
  {
    id: 'p040',
    category: 'audio',
    title: { ar: 'سماعة قرآن مضيئة لمسية', en: 'Touch LED Quran Speaker Lamp' },
    price: 13,
    image: '/products/p040.jpg',
  },
  {
    id: 'p041',
    category: 'electronics',
    title: { ar: 'كاميرا تصوير للأطفال', en: 'Kids Digital Camera' },
    price: 9,
    image: '/products/p041.jpg',
  },
  {
    id: 'p042',
    category: 'beauty',
    title: { ar: 'فرشاة أسنان كهربائية Sonic', en: 'Sonic Electric Toothbrush' },
    price: 9,
    image: '/products/p042.jpg',
  },
  {
    id: 'p043',
    category: 'electronics',
    title: { ar: 'بروجكتر صغير 4K أسود بتطبيقات', en: 'Mini 4K Projector w/ Apps' },
    price: 28,
    image: '/products/p043.jpg',
  },
  {
    id: 'p044',
    category: 'audio',
    title: { ar: 'سماعات لاسلكية بتصميم بديل', en: 'Wireless Earbuds (Pro-style)' },
    price: 12,
    image: '/products/p044.jpg',
  },
  {
    id: 'p045',
    category: 'electronics',
    title: { ar: 'جرس باب ذكي بشاشة (بدون واي فاي)', en: 'Smart Video Doorbell (No WiFi)' },
    price: 20,
    image: '/products/p045.jpg',
  },
  {
    id: 'p046',
    category: 'home',
    title: { ar: 'عصارة وخلاط طعام 4 في 1', en: '4-in-1 Juicer & Blender' },
    price: 19,
    image: '/products/p046.jpg',
  },
  {
    id: 'p047',
    category: 'electronics',
    title: { ar: 'جهاز لوحي "F10" بغطاء لوحة مفاتيح', en: 'F10 Tablet with Keyboard Cover' },
    price: 31,
    image: '/products/p047.jpg',
  },
  {
    id: 'p048',
    category: 'electronics',
    title: { ar: 'ساعة يد كلاسيكية "ROCK 21" مع 4 أساور', en: 'ROCK 21 Watch w/ 4 Straps' },
    price: 11,
    image: '/products/p048.jpg',
  },
  {
    id: 'p049',
    category: 'beauty',
    title: { ar: 'مسدس تدليك عضلات فضي', en: 'Silver Massage Gun' },
    price: 12,
    image: '/products/p049.jpg',
  },
  {
    id: 'p050',
    category: 'beauty',
    title: { ar: 'ماكينة قص شعر DENGLENG بقاعدة شحن', en: 'DENGLENG Hair Clipper w/ Dock' },
    price: 10,
    image: '/products/p050.jpg',
  },
  {
    id: 'p051',
    category: 'audio',
    title: { ar: 'لمبة إضاءة بسماعة قرآن بلوتوث', en: 'Quran Bluetooth Speaker Bulb' },
    price: 10,
    image: '/products/p051.jpg',
  },
  {
    id: 'p052',
    category: 'audio',
    title: { ar: 'ساعة منبه رقمية بسماعة بلوتوث', en: 'Digital Alarm Clock BT Speaker' },
    price: 13,
    image: '/products/p052.jpg',
  },
  {
    id: 'p053',
    category: 'beauty',
    title: { ar: 'ماكينة قص شعر Kemei KM-1791', en: 'Kemei KM-1791 Hair Clipper' },
    price: 13,
    image: '/products/p053.jpg',
  },
  {
    id: 'p054',
    category: 'electronics',
    title: { ar: 'كاميرا مراقبة وهمية للردع (زوج)', en: 'Fake Deterrent Camera (Pair)' },
    price: 11,
    image: '/products/p054.jpg',
  },
  {
    id: 'p055',
    category: 'electronics',
    title: { ar: 'ساعة ذكية "S10 Pro Max" مع 7 أساور', en: 'S10 Pro Max Watch w/ 7 Straps' },
    price: 10.,
    image: '/products/p055.jpg',
  },
  {
    id: 'p056',
    category: 'beauty',
    title: { ar: 'مسدس تدليك عضلات أسود مع ملحقات', en: 'Black Massage Gun w/ Heads' },
    price: 15,
    image: '/products/p056.jpg',
  },
  {
    id: 'p057',
    category: 'electronics',
    title: { ar: 'جرس باب فيديو ذكي بشاشة 4.3 بوصة', en: 'Smart Video Doorbell 4.3in' },
    price: 20,
    image: '/products/p057.jpg',
  },
  {
    id: 'p058',
    category: 'beauty',
    title: { ar: 'ماكينة حلاقة صغيرة فضية (طقم 3 قطع)', en: 'Mini Shaver Silver (3-Pack)' },
    price: 10,
    image: '/products/p058.jpg',
  },
  {
    id: 'p059',
    category: 'audio',
    title: { ar: 'لمبة إضاءة بسماعة بلوتوث "Music Bulb"', en: 'Music Bulb BT Speaker Lamp' },
    price: 8,
    image: '/products/p059.jpg',
  },
  {
    id: 'p060',
    category: 'audio',
    title: { ar: 'سماعة قرآن Equantu SQ200 مع ريموت', en: 'Equantu SQ200 Quran Speaker' },
    price: 10,
    image: '/products/p060.jpg',
  },
  {
    id: 'p061',
    category: 'beauty',
    title: { ar: 'ميزان وزن رقمي زجاجي شفاف', en: 'Digital Glass Body Scale' },
    price: 9,
    image: '/products/p061.jpg',
  },
  {
    id: 'p062',
    category: 'electronics',
    title: { ar: 'كاميرا واي فاي صغيرة مخفية (فردية)', en: 'Mini WiFi Hidden Camera (Single)' },
    price: 10,
    image: '/products/p062.jpg',
  },
  {
    id: 'p063',
    category: 'audio',
    title: { ar: 'سماعات Monster لاسلكية بعلبة مميزة', en: 'Monster Wireless Earbuds' },
    price: 12,
    image: '/products/p063.jpg',
  },
  {
    id: 'p064',
    category: 'beauty',
    title: { ar: 'ماكينة حلاقة وتشذيب Kemei 3 في 1', en: 'Kemei 3-in-1 Shaver & Trimmer' },
    price: 8,
    image: '/products/p064.jpg',
  },
  {
    id: 'p065',
    category: 'beauty',
    title: { ar: 'جهاز تشذيب نسائي شامل 4 في 1', en: 'Women\'s 4-in-1 Grooming Kit' },
    price: 10,
    image: '/products/p065.jpg',
  },
  {
    id: 'p066',
    category: 'home',
    title: { ar: 'قلاية هوائية Best Silver Crest 13.5 لتر', en: 'Best Silver Crest Air Fryer 13.5L' },
    price: 27,
    image: '/products/p066.jpg',
  },
  {
    id: 'p067',
    category: 'beauty',
    title: { ar: 'طقم ماكينات حلاقة ذهبية فينتدج', en: 'Vintage Gold Trimmer Set' },
    price: 14,
    image: '/products/p067.jpg',
  },
  {
    id: 'p068',
    category: 'beauty',
    title: { ar: 'ماكينة قص شعر ذهبية فينتدج', en: 'Vintage Gold Hair Clipper' },
    price: 10,
    image: '/products/p068.jpg',
  },
  {
    id: 'p069',
    category: 'audio',
    title: { ar: 'سماعات أذن لاسلكية بعلبة دائرية', en: 'Wireless Earbuds Round Case' },
    price: 10,
    image: '/products/p069.jpg',
  },
  {
    id: 'p070',
    category: 'electronics',
    title: { ar: 'نظارة شمسية بسماعة بلوتوث (نصف إطار)', en: 'BT Audio Sunglasses (Half-Frame)' },
    price: 9,
    image: '/products/p070.jpg',
  },
  {
    id: 'p071',
    category: 'audio',
    title: { ar: 'سماعة رأس سلكية ASD رياضية', en: 'ASD Sport Wired Headphone' },
    price:10,
    image: '/products/p071.jpg',
  },
  {
    id: 'p072',
    category: 'electronics',
    title: { ar: 'كاميرا واي فاي صغيرة مخفية (طقم 3 قطع)', en: 'Mini WiFi Hidden Camera (3-Pack)' },
    price: 20,
    image: '/products/p072.jpg',
  },
  {
    id: 'p073',
    category: 'beauty',
    title: { ar: 'جهاز تنظيف بالحجامة الكهربائية (زوج)', en: 'Electric Cupping Massage Device (Pair)' },
    price: 10,
    image: '/products/p073.jpg',
  },
  {
    id: 'p074',
    category: 'beauty',
    title: { ar: 'ماكينة حلاقة متعددة الوظائف Kemei 3x1 للرجال', en: 'Kemei 3-in-1 Multi-Function Grooming Kit' },
    price: 12,
    image: '/products/p074.jpg',
  },
  {
    id: 'p075',
    category: 'electronics',
    title: { ar: 'قلم كاميرا مخفية', en: 'Spy Pen Camera' },
    price: 11,
    image: '/products/p075.jpg',
  },
]

export const locations: Record<Language, Record<string, string[]>> = {
  ar: {
    'العاصمة': ['السالمية', 'دسمان', 'الشرق', 'المرقاب', 'الدعية', 'الدسمة', 'كيفان', 'قرطبة'],
    'حولي': ['حولي', 'السالمية', 'الجابرية', 'مشرف', 'الرميثية', 'بيان', 'سلوى'],
    'الفروانية': ['الفروانية', 'العارضية', 'جليب الشيوخ', 'الرابية', 'الأندلس', 'خيطان'],
    'مبارك الكبير': ['صباح السالم', 'القرين', 'العدان', 'القصور', 'أبو فطيرة'],
    'الأحمدي': ['الأحمدي', 'الفحيحيل', 'المهبولة', 'الفنطاس', 'أبو حليفة', 'الرقة'],
    'الجهراء': ['الجهراء', 'الصليبية', 'العيون', 'النعيم', 'القصر'],
  },
  en: {
    'Al Asimah': ['Salmiya', 'Dasman', 'Sharq', 'Murgab', 'Daiya', 'Dasma', 'Kaifan', 'Qortuba'],
    'Hawalli': ['Hawalli', 'Salmiya', 'Jabriya', 'Mishref', 'Rumaithiya', 'Bayan', 'Salwa'],
    'Farwaniya': ['Farwaniya', 'Ardiya', 'Jleeb Al-Shuyoukh', 'Rabiya', 'Andalous', 'Khaitan'],
    'Mubarak Al-Kabeer': ['Sabah Al-Salem', 'Qurain', 'Adan', 'Qusour', 'Abu Fatira'],
    'Ahmadi': ['Ahmadi', 'Fahaheel', 'Mahboula', 'Fintas', 'Abu Halifa', 'Riqqa'],
    'Jahra': ['Jahra', 'Sulaibiya', 'Oyoun', 'Naeem', 'Qasr'],
  },
}